name: medicine_system
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # main state management use
  flutter_riverpod: ^3.4.2
  intl: ^0.20.2

  # route related
  go_router: ^18.0.0

  # payment related
  app_links: ^7.2.1

  # storage
  shared_preferences: ^2.5.5

  # #1 Secure token storage (Android Keystore / iOS Keychain)
  flutter_secure_storage: ^11.0.0

  # environment secure variable
  flutter_dotenv: ^6.0.1

  # api services
  dio: ^5.11.0
  http_parser: ^4.1.2
  mime: ^2.1.0
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^3.1.6
  connectivity_plus: ^7.3.1

  # translator
  translator: ^1.0.4+1
  html: ^0.15.7

  # image related
  cached_network_image: ^4.0.0
  flutter_cache_manager: ^3.4.2
  image_picker: ^1.2.3

  # ui related
  permission_handler: ^13.0.1
  readmore: ^3.0.0
  skeletonizer: ^2.1.3
  flutter_widget_from_html_core: ^0.17.3
  cupertino_icons: ^1.0.9

  # notification related
  flutter_local_notifications: ^22.3.0
  firebase_messaging: ^16.6.0
  firebase_core: ^4.14.0
  device_info_plus: ^13.2.0

  # Flutter 3.44.0 flutter_test compatibility
  vector_math: ^2.2.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  change_app_package_name: ^1.5.0
  # dart run change_app_package_name:main com.new.package.name
  # if need only android --android
  # if need only ios --ios

flutter:
  uses-material-design: true

  # local all assets
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - .env

  # local all font
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf